version: "3.8"
services:
  db:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ATPOS
    ports:
      - "7001:5432"
volumes:
  pgdata: